### ISSUE TITLE
Find performance metrics

### ISSUE THREAD

**Issue by theodorhusefest** [theodorhusefest/microgrid-mpc#9]
Find a way to evaluate the performance of the microgrid

**Comment by electednico** [comment]
For brainstorming.
This is what Sintef uses as key performance metrics in their report:
PV-self consumption ratio (the amount of energy produced by PV used to cover the load)
Self-dependency ratio (relative amount of consumed power provided directly by the PV-system or provided by the PV-system after being storred in the BESS)
Relative battery usage (The number of hours the BESS was used to cover a load divided by the number of hours)
Relative losses (Losses  divided by total feed-in)
